name = "cloudflare-workers-typescript-esbuild-esm"
type = "javascript"
account_id = ""
workers_dev = true

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.js"

[durable_objects]
bindings = []
